---
- name: Install nfs-utils package
  yum: 
    name: nfs-utils
    state: present

- name: Create directories
  file:
    path: /var/export/{{ item.name }}
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0777
    state: directory
  with_items: folders

- name: Add line in file etc exports
  lineinfile: 
   dest: /etc/exports
   insertafter: EOF
   line: /var/export/{{ item }} *(rw,root_squash,no_wdelay)
  with_items: folders
  
- name: Modify idmapd with hostname
  lineinfile:
    dest: /etc/idmapd.conf
    regexp: "^Domain ="
    insertafter: "^#Domain ="
    line: "Domain = {{ nfs_internal_hostname }}"
  notify: restart_rpcidmapd
        
- name: Enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap    
    
#- name: Set up iptables rules
#  copy: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables  

- name: Backup iptables
  shell: "iptables-save > /etc/sysconfig/iptables"

# use this until 2.0 for iptables module
- name: Open the correct iptables ports
  lineinfile: 
    dest: "/etc/sysconfig/iptables"
    regexp: "^-A OS_FIREWALL_ALLOW -p {{ item.protocol }} -m state --state NEW -m {{ item.protocol }} --dport {{ item.port }} -j ACCEPT$"
    line: "-A OS_FIREWALL_ALLOW -p {{ item.protocol }} -m state --state NEW -m {{ item.protocol }} --dport {{ item.port }} -j ACCEPT"
    insertafter: "^-A FORWARD -j REJECT --reject-with"
  with_items:
    - { protocol: tcp, port: 111 }
    - { protocol: tcp, port: 2049 }
    - { protocol: tcp, port: 20048 }
    - { protocol: tcp, port: 50825 }
    - { protocol: tcp, port: 53248 }
    - { protocol: udp, port: 53248 }    
  notify: restart iptables
  
#- name: Restore iptables
#  shell: "iptables-restore < /etc/sysconfig/iptables"

- name: Modify sysconfig/nfs RPCMOUNTOPTS
  replace:
    dest: /etc/sysconfig/nfs
    regexp: '(\s+)^RPCMOUNTDOPTS=""'
    replace: '\1RPCMOUNTDOPTS="-p 20048"'

- name: Modify sysconfig/nfs STATDARG
  replace:
    dest: /etc/sysconfig/nfs
    regexp: '(\s+)^STATDARG=""'
    replace: '\1STATDARG="-p 50825"'
    
- name: Modify sysctl.conf tcpport
  lineinfile: 
   dest: /etc/sysctl.conf
   insertafter: EOF
   line: fs.nfs.nlm_tcpport=53248
  
- name: Modify sysctl.conf udpport
  lineinfile: 
   dest: /etc/sysctl.conf
   insertafter: EOF
   line: fs.nfs.nlm_udpport=53248

- name: sysctl -p
  command: sysctl -p

- name: SELinux - virt_use_nfs
  command: setsebool -P virt_use_nfs 1

- name: SELinux - virt_sandbox_use_nfs
  command: setsebool -P virt_sandbox_use_nfs 1

- name: Restart nfs
  service: 
    name: nfs
    state: restarted
