---
- hosts: localhost
  connection: local
  tasks:
    - name: upgrade atomic-openshift utils and clients
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - atomic-openshift-utils
        - atomic-openshift-clients
            
- hosts: openshift_master
  remote_user: root
  vars_files: 
    - upgrade_vars.yml
  tasks:
    - name: update config file IMAGE_VERSION
      lineinfile:
        dest: "{{ item }}"
        regexp: "^IMAGE_VERSION="
        line: "IMAGE_VERSION={{ image_version }}"      
      with_items:
        - /etc/sysconfig/atomic-openshift-master
        - /etc/sysconfig/atomic-openshift-node
        - /etc/sysconfig/openvswitch
      register: image_version_update

    - name: restart openshift services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - atomic-openshift-master
        - openvswitch   
        - atomic-openshift-node
      when: image_version_update|changed

    - include: upgrade_core.yml 

    - name: openshift node service needs to restart again
      service:
        name: atomic-openshift-node
        state: restarted    
    
    - name: update openshift proxy command to correct version
      lineinfile:
        dest: /usr/local/bin/openshift
        regexp: "^image_tag="
        line: "image_tag={{ image_version }}" 
        
    - name: check if openshift master api is ready
      command: >
        curl --silent --cacert /etc/origin/master/ca.crt
        {{ master_url }}/healthz/ready
      register: api_available_output
      until: api_available_output.stdout == 'ok'
      retries: 30
      delay: 10
    
    - name: login to openshift
      command: "oc login {{ master_url }} -u admin -p password --insecure-skip-tls-verify=true"
      delegate_to: localhost
        
    - name: reconcile cluster roles
      shell: > 
        oc adm policy reconcile-cluster-roles 
        --additive-only=true 
        --confirm
      delegate_to: localhost
    
    - name: reconcile cluster role bindings
      shell: > 
        oc adm policy reconcile-cluster-role-bindings 
        --exclude-groups=system:authenticated 
        --exclude-groups=system:authenticated:oauth 
        --exclude-groups=system:unauthenticated 
        --exclude-users=system:anonymous 
        --additive-only=true 
        --confirm
      delegate_to: localhost
    
    - name: reconcile cluster roles again
      shell: > 
        oc adm policy reconcile-cluster-roles 
        --additive-only=true 
        --confirm   
      delegate_to: localhost

- hosts: openshift_nodes
  remote_user: root
  vars_files: 
    - upgrade_vars.yml
  serial: 1
  tasks:
    - name: login to openshift
      command: "oc config use-context {{ default_context }}"
      delegate_to: localhost
            
    - name: make node unschedulable
      command: oc adm manage-node {{ inventory_hostname }} --schedulable=false
      delegate_to: localhost
   
    - name: evacuate pods from node
      command: oc adm manage-node {{ inventory_hostname }} --evacuate --force
      delegate_to: localhost

    - name: update config file IMAGE_VERSION
      lineinfile:
        dest: "{{ item }}"
        regexp: "^IMAGE_VERSION="
        line: "IMAGE_VERSION={{ image_version }}"      
      with_items:
        - /etc/sysconfig/atomic-openshift-node
        - /etc/sysconfig/openvswitch
      register: image_version_update
        
    - name: restart openshift services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - openvswitch   
        - atomic-openshift-node
      when: image_version_update|changed

    - include: upgrade_core.yml         
      
    - name: make node schedulable
      command: oc adm manage-node {{ inventory_hostname }} --schedulable=true
      delegate_to: localhost
      
- hosts: localhost
  remote_user: root
  connection: local
  vars_files: 
    - upgrade_vars.yml
  tasks:
    - name: login to openshift
      command: "oc config use-context {{ default_context }}"
  
    - name: switch to project default
      command: "oc project default"        
      
    - name: update router
      command: oc patch dc/router -p '{"spec":{"template":{"spec":{"containers":[{"name":"router", "image":"openshift3/ose-haproxy-router:{{ image_version }}"}]}}}}'         
    
    - name: update registry
      command: oc patch dc/docker-registry -p '{"spec":{"template":{"spec":{"containers":[{"name":"registry", "image":"openshift3/ose-docker-registry:{{ image_version }}"}]}}}}'               
      
    - name: create image streams
      command:  oc create -n openshift -f /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/latest/{{ item }}
      with_items:
        - "image-streams/image-streams-rhel7.json"
        - "db-templates"
        - "xpaas-streams"
        - "xpaas-templates"
      ignore_errors: true        
    
    - name: replace image streams
      command: oc replace -n openshift -f /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/latest/{{ item }}
      with_items:
        - "image-streams/image-streams-rhel7.json"
        - "db-templates"
        - "quickstart-templates"
        - "xpaas-streams"
        - "xpaas-templates"
        - "infrastructure-templates/enterprise"

    - name: get image streams
      shell: "oc get is -n openshift | awk 'NR>1 { print $1 }'"
      register: is_output
    
    # sso will fail        
    - name: import latest images
      command: oc import-image -n openshift "{{ item }}"
      with_items: is_output.stdout_lines
      ignore_errors: true
      
    - name: change to project logging
      command: oc project logging
      
    - name: determine elastic search DC
      shell: "oc get dc | awk '/logging-es-[a-zA-Z0-9]*/{ print $1 }'"
      register: logging_es_out

    - name: scale down logging pods
      command: oc scale dc/{{ item }} --replicas=0
      with_items:
        - "logging-fluentd"
        - "logging-kibana"
    #    - "logging-kibana-ops"
        - "{{ logging_es_out.stdout }}"
      
    - name: update logging images
      command: oc import-image {{ item }}:{{ logging_image_version }} --from registry.access.redhat.com/openshift3/{{ item }}:{{ logging_image_version }}
      with_items:
        - logging-auth-proxy
        - logging-kibana
        - logging-elasticsearch
        - logging-fluentd

    - name: update es dc
      command: oc patch dc/{{ logging_es_out.stdout }} -p '{"spec":{"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["elasticsearch"],"from":{"kind":"ImageStreamTag","name":"logging-elasticsearch:{{ logging_image_version }}"}}}]}}'          

    - name: update fluentd dc
      command: oc patch dc/logging-fluentd -p '{"spec":{"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["fluentd-elasticsearch"],"from":{"kind":"ImageStreamTag","name":"logging-fluentd:{{ logging_image_version }}"}}}]}}'          

    - name: update kibana dc
      command: oc patch dc/logging-kibana -p '{"spec":{"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["kibana"],"from":{"kind":"ImageStreamTag","name":"logging-kibana:{{ logging_image_version }}"}}},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["kibana-proxy"],"from":{"kind":"ImageStreamTag","name":"logging-auth-proxy:{{ logging_image_version }}"}}}]}}'
    
# not needed because of image change trigger above          
#    - name: deploy dcs 
#      command: oc deploy {{ item }} --latest
#      with_items:
#        - "{{ logging_es_out.stdout }}"
#        - "logging-fluentd"
#        - "logging-kibana"
                  
    - name: scale up logging pods
      shell: oc scale dc/{{ item }}
      with_items:
        - "{{ logging_es_out.stdout }} --replicas=1"
        - "logging-fluentd --replicas=2"
        - "logging-kibana --replicas=1"
    #    - "oc scale dc/logging-kibana-ops --replicas=0"
    
    - name: upgrade metrics
      shell: >
        oc process metrics-deployer-template -n openshift 
        -v USE_PERSISTENT_STORAGE=false 
        -v HAWKULAR_METRICS_HOSTNAME={{ metrics_url }}
        -v MODE=refresh | oc create -f -
