---    
# before running this, openshift needs to be installed
- hosts: openshift_master
  remote_user: root
  vars:
    folders:
      - { name: vol1, owner: 1000, group: 0 } # logging
      - { name: vol2, owner: nfsnobody, group: nfsnobody}  # metrics
      - { name: vol3, owner: nfsnobody, group: nfsnobody}  # registry
      - { name: vol4, owner: nfsnobody, group: nfsnobody}  
      - { name: vol5, owner: nfsnobody, group: nfsnobody}  
      - { name: vol6, owner: nfsnobody, group: nfsnobody} 
      
  roles:
    - nfs
    - registry
    - router
    - logging
    - metrics
